[engine]
rate = 5                            # 速率
duration = "20s"                     # 持续时间
cap = 2                             # 客户端虚拟机数量
instant=1                            # 每个批次发的交易数
wait="0s"                            # 获取cap最大等待时间

[client]
script = "benchmark/hyperchain/local/script.lua"  # 脚本
type = "flato"                                    # 区块链类型
config = "benchmark/hyperchain/local/hyperchain"  # 区块链SDK配置路径
contract = "benchmark/hyperchain/local/contract"  # 合约目录路径
plugin = "./hyperchain.so"                        # 插件路径

[client.options] # 客户端选项
request="rpc"

[recorder.log]
dump=false                  # 日志是否输出
dir="./logs"                # 日志输出路径
level="notice"              # 日志等级

[recorder.csv]
dir="./csv"                 # csv文件输出路径

[recorder.influxdb]
url="http://localhost:8086"                 #influxdb url
database="hyperbench"
username="admin"
password="admin"

[verify]
enable=true
percentage=0.1




