[engine]
rate = 1                                # 速率
duration = "30s"                        # 持续时间
cap = 1                                 # 客户端虚拟机数量
instant=1                               # 每个批次发的交易数
wait="0s"                               # 获取cap最大等待时间

[client]
script = "benchmark/hyperchain/evmType/script.lua"  # 脚本
type = "flato"                                      # 区块链类型
config = "benchmark/hyperchain/evmType/hyperchain"  # 区块链SDK配置路径
contract = "benchmark/hyperchain/evmType/contract"  # 合约目录路径
plugin = "./hyperchain.so"                          # 插件路径

[client.options] # 客户端选项
sign = "ECDSA"
request="rpc"