name: Sync
on:
  push:
    branches:
      - master
      - develop

jobs:
  sync:
    name: Sync Code To Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY_LMM }}
        with:
          source-repo: "git@github.com:hyperbench/hyperbench.git"
          destination-repo: "git@gitee.com:hyperbench/hyperbench.git"
