[engine]
rate = 10                           # 速率
duration = "20s"     		      # 持续时间
cap = 10                             # 客户端虚拟机数量
instant=10                            # 每个批次发的交易数
wait="0s"                             # 获取cap最大等待时间
#urls = ["localhost:8085","localhost:8086"]                 # 若不设置或者长度为0则在本地启动worker

[client]
script = "benchmark/hyperchain/hvmContract/script.lua"  # 脚本
type = "flato"                                    # 区块链类型
config = "benchmark/hyperchain/hvmContract/hyperchain"  # 区块链SDK配置路径
contract = "benchmark/hyperchain/hvmContract/contract"  # 合约目录路径
plugin = "./hyperchain.so"                        # 插件路径

[client.options] # 客户端选项
keystore = "benchmark/hyperchain/hvm_method_map/keystore/sm2"
sign="sm2"
request="rpc"

[recorder.log]
dump=false                  # 日志是否输出
dir="./logs"                # 日志输出路径
level="notice"              # 日志等级

[recorder.csv]
dir="./csv"                 # csv文件输出路径